package presentation.interfaces;

import data.CategoriaDAO;
import data.MarcaDAO;
import data.interfaces.CrudProductoInterface;
import data.ProductoDAO;
import data.UbicacionDAO;
import database.Conexion;
import entities.Producto;
import utils.Utils;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class FrmAddProducto extends javax.swing.JPanel {

    boolean isEdition = false;
    entities.Producto ProductoEditado;
    DecimalFormat formato = new DecimalFormat("#.00");

    public FrmAddProducto() {
        initComponents();
        InitStyles();
    }

    public FrmAddProducto(entities.Producto produc) {
        initComponents();
        isEdition = true;
        ProductoEditado = produc;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del producto");
        precioCompraTxt.putClientProperty("JTextField.placeholderText", "Ingrese el precio de compra.");
        precioVentaTxt.putClientProperty("JTextField.placeholderText", "Ingrese el precio de venta.");
        descripcionTxt.putClientProperty("JTextField.placeholderText", "Ingrese la descripcion.");
        categoriaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la categoria.");
        marcaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la marca del producto.");
//        fechaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la fecha de actualización del producto.");
        stockTxt.putClientProperty("JTextField.placeholderText", "Ingrese el stock total del pruducto.");
        stockminimoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el stock minimo del producto.");

        if (isEdition) {
            title.setText("Editar producto");
            button.setText("Guardar");

            if (ProductoEditado != null) {
                nombreTxt.setText(ProductoEditado.getNombre());
                precioCompraTxt.setText(formato.format(ProductoEditado.getPrecioCompra()));
                precioVentaTxt.setText(formato.format(ProductoEditado.getPrecioVenta()));
                descripcionTxt.setText(ProductoEditado.getDescripcion());
                categoriaTxt.setText(ProductoEditado.getIdCategoria() + "");
                marcaTxt.setText(ProductoEditado.getIdMarca() + "");
//                fechaTxt.setText(ProductoEditado.getFechaUltimaActualizacion());
                stockTxt.setText(ProductoEditado.getStock() + "");
                stockminimoTxt.setText(ProductoEditado.getStockMinimo() + "");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        precioCompraTxt = new javax.swing.JTextField();
        catLbl = new javax.swing.JLabel();
        precioVentaTxt = new javax.swing.JTextField();
        edLbl = new javax.swing.JLabel();
        descripcionTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        langLbl = new javax.swing.JLabel();
        categoriaTxt = new javax.swing.JTextField();
        pagsLbl = new javax.swing.JLabel();
        marcaTxt = new javax.swing.JTextField();
        descLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        stockTxt = new javax.swing.JTextField();
        stockminimoTxt = new javax.swing.JTextField();
        dispLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        ubicacionTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Añadir nuevo producto");

        titleLbl.setText("Nombre");

        authorLbl.setText("Precio Compra");

        catLbl.setText("Precio Venta");

        edLbl.setText("Descripción");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        langLbl.setText("Categoría");

        categoriaTxt.setToolTipText("");

        pagsLbl.setText("Marca");

        marcaTxt.setToolTipText("");

        descLbl.setText("Cual es la Ubicación del Producto");

        stockLbl.setText("Stock");
        stockLbl.setToolTipText("");

        stockTxt.setToolTipText("");

        stockminimoTxt.setToolTipText("");

        dispLbl.setText("Stock Minimo");

        button.setBackground(new java.awt.Color(255, 102, 0));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Subir");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(76, 76, 76)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(langLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(stockLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(dispLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(stockminimoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ubicacionTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(title)
                .addGap(8, 8, 8)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(precioCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(catLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(precioVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(langLbl)
                        .addGap(4, 4, 4)
                        .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pagsLbl)
                        .addGap(4, 4, 4)
                        .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(descLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubicacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockLbl)
                            .addComponent(dispLbl))
                        .addGap(4, 4, 4)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockminimoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        String nombre = nombreTxt.getText();
        String precioCompra = precioCompraTxt.getText();
        String precioVenta = precioVentaTxt.getText();
        String descripcion = descripcionTxt.getText();
        String categoriaNombre = categoriaTxt.getText();
        String marcaNombre = marcaTxt.getText();
        String ubicacionNombre = ubicacionTxt.getText(); // Nuevo campo para ubicación
        String stock = stockTxt.getText();
        String stockminimo = stockminimoTxt.getText();

        // Validaciones para los campos
        if (nombre.isEmpty() || precioCompra.isEmpty() || precioVenta.isEmpty() || descripcion.isEmpty()
                || categoriaNombre.isEmpty() || marcaNombre.isEmpty() || ubicacionNombre.isEmpty()
                || stock.isEmpty() || stockminimo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nombreTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(stock) || !Utils.isNumeric(stockminimo)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos Stock y Stock Mínimo deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            stockTxt.requestFocus();
            return;
        }

        // Obtener la fecha y hora exacta en el momento del clic
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fechaActual = sdf.format(new Date());

        try {
            ProductoDAO dao = new ProductoDAO();
            CategoriaDAO categoriaDAO = new CategoriaDAO(); // DAO para Categoría
            MarcaDAO marcaDAO = new MarcaDAO();             // DAO para Marca
            UbicacionDAO ubicacionDAO = new UbicacionDAO(); // DAO para Ubicación

            // Obtener o registrar categoría
            int idCategoria = categoriaDAO.obtenerORegistrarPorNombre(categoriaNombre);
            // Obtener o registrar marca
            int idMarca = marcaDAO.obtenerORegistrarPorNombre(marcaNombre);
            // Obtener o registrar ubicación
            int idUbicacion = ubicacionDAO.obtenerORegistrarPorNombre(ubicacionNombre);

            // Crear el objeto Producto con los valores ingresados
            Producto produc = new Producto(0, idCategoria, idMarca, idUbicacion,
                    nombre, descripcion,
                    Double.parseDouble(precioCompra), Double.parseDouble(precioVenta),
                    Integer.parseInt(stock), Integer.parseInt(stockminimo),
                    fechaActual, true);

            if (!isEdition) {
                dao.registrar(produc);  // Insertar el producto nuevo
            } else {
                dao.modificar(produc);  // Modificar un producto existente
            }

            String successMsg = isEdition ? "modificado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this, "Producto " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                // Limpiar campos solo si es un nuevo producto
                nombreTxt.setText("");
                precioCompraTxt.setText("");
                precioVentaTxt.setText("");
                descripcionTxt.setText("");
                categoriaTxt.setText("");
                marcaTxt.setText("");
                ubicacionTxt.setText(""); // Limpiar campo ubicación
                stockTxt.setText("");
                stockminimoTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el producto. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }


    }//GEN-LAST:event_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLbl;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel catLbl;
    private javax.swing.JTextField categoriaTxt;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descripcionTxt;
    private javax.swing.JLabel dispLbl;
    private javax.swing.JLabel edLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel langLbl;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel pagsLbl;
    private javax.swing.JTextField precioCompraTxt;
    private javax.swing.JTextField precioVentaTxt;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JTextField stockminimoTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField ubicacionTxt;
    // End of variables declaration//GEN-END:variables
}
